version: '3.0'
services:
  app:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    ports:
        - "3000:3000"
    command: npm start
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      TZ: 'America/Sao_Paulo'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '${DB_HOST}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf'